Link account command
fylein/fyle-teams-app pull request #11
Opened 2022-01-18 06:37 UTC by shreyanshss7

2022-01-18 07:01 UTC, gokulk16 requested changes

2022-01-18 07:01 UTC, gokulk16 commented on fyle_teams_app/views/handlers/command_handlers.py
> +
need not have these many line breaks after every line. Please use line breaks only when there is a logical separation

2022-01-19 07:49 UTC, shreyanshss7 commented on fyle_teams_app/models/users.py
> +    def track_fyle_account_unlinked(event_data) -> None:
TODO: All the trackings should be in a separate module/file. Will take care of this in a separate PR.

2022-01-20 04:55 UTC, gokulk16 requested changes

2022-01-20 04:55 UTC, gokulk16 commented on fyle_teams_app/models/users.py
> +
why is this unnecesary line breaks?

2022-01-20 04:55 UTC, gokulk16 commented on fyle_teams_app/views/authorisation/team.py
> +
line breaks is not for every line :fml:

2022-01-20 04:55 UTC, gokulk16 commented on fyle_teams_app/views/handlers/action_handlers.py
> +
remove line break

2022-01-20 04:55 UTC, gokulk16 commented on fyle_teams_app/views/handlers/command_handlers.py
remove linebreak

2022-01-20 04:55 UTC, gokulk16 commented on fyle_teams_app/views/handlers/command_handlers.py
> +
remove linebreak

2022-01-20 04:55 UTC, gokulk16 commented on fyle_teams_app/views/handlers/command_handlers.py
> +            processing_message = 'Hey we are unlinking your Fyle account with Microsft Teams, we will send a message once it is done'
can remove 'Hey'

2022-01-20 05:46 UTC, gokulk16 approved these changes

2022-01-20 05:46 UTC, gokulk16 commented on fyle_teams_app/views/handlers/action_handlers.py
> +                    # Track report approved
avoid these kind of code comments where it is not saying anything beyond the function name.
can remove.

2022-01-20 05:46 UTC, gokulk16 commented on fyle_teams_app/views/handlers/action_handlers.py
3 line breaks? Why Shreyansh Why

2022-01-20 05:46 UTC, gokulk16 commented on fyle_teams_app/models/users.py
> -
remove line break

2022-01-20 05:46 UTC, gokulk16 commented on fyle_teams_app/views/authorisation/team.py
> +
please remove.

2022-01-20 05:46 UTC, gokulk16 commented on fyle_teams_app/views/authorisation/team.py
> +
having line break to call a function is fine. can also group a function call's related parameters also together.
example this line.
`user_details` is only used in the next line(a function call). It's fine to group these 2 together.

2022-01-20 05:46 UTC, gokulk16 commented on fyle_teams_app/models/users.py
> -
the above `tracking`  object is used only for the next line. So can have it together without line breaks.

2022-01-20 05:53 UTC, shreyanshss7 commented on fyle_teams_app/views/authorisation/team.py
> +
Agreed

2022-01-20 05:53 UTC, shreyanshss7 commented on fyle_teams_app/views/handlers/action_handlers.py
my bad here

2022-01-20 06:01 UTC, merged