Add fyle_org_name column to users table and include it in all trackers
fylein/fyle-teams-app pull request #24
Opened 2022-05-25 21:58 UTC by jatzz10

### Issue
For teams app, we don't send `fyle_org_name` as part of any trackers in segment

### Fix
1. Add new column `fyle_org_name` in `users` table
2. Run django migrations and apply them (new columns would have been added)
3. Since, already existing old records will not be having any value in `fyle_org_name` column, we will have to manually fetch the org-name for all existing records and update (add) the org-name for all records.

2022-05-25 22:01 UTC, jatzz10 commented on fyle_teams_app/migrations/0002_user_fyle_org_name.py
> +    ]
this file is auto-generated by django after when we -
1. go into the teams-app service in local (`docker-compose exec teams-app-service bash`)
2. run migrations there (`python manage.py makemigrations`)

2022-05-26 08:11 UTC, gokulk16 commented
> 3\. Since, already existing old records will not be having any value in `fyle_org_name` column, we will have to manually fetch the org-name for all existing records and update (add) the org-name for all records.

can you add the specific script to run for this also in the same PR.
can create a new folder called specific_DB_migrations and add the SQL script into it

2022-05-26 08:11 UTC, gokulk16 requested changes
neededd the sql script to populate old records' org_name.

2022-05-30 08:39 UTC, gokulk16 commented on scripts/add_fyle_org_name_migration_changes.sql
> +) to 'slack_orgs.csv' csv header;
these are teams orgs no?
if yes, then can rename file to `teams_orgs.csv`

2022-05-30 10:34 UTC, jatzz10 commented on scripts/add_fyle_org_name_migration_changes.sql
> +-- Script to update the 'fyle_org_name' column with respective org names
mention teams db

2022-05-30 10:38 UTC, jatzz10 commented on scripts/add_fyle_org_name_migration_changes.sql
> +-- Script to update the 'fyle_org_name' column with respective org names
add specific scripts for updating

2022-06-02 12:45 UTC, gokulk16 requested changes

2022-06-02 12:45 UTC, gokulk16 commented on scripts/add_fyle_org_name_migration_changes/fetch_org_names_from_prod_dbs.sql
> +    select
selecting all the orgs is a huge operation. can we do some filtering here itself?

2022-06-02 12:46 UTC, gokulk16 commented on scripts/add_fyle_org_name_migration_changes/fetch_org_names_from_prod_dbs.sql
> +    select
we can dump the teams_db_orgs into a table in here and pull only the needed data. can u try that

2022-06-02 16:23 UTC, gokulk16 approved these changes

2022-06-03 07:22 UTC, merged