Made Amount Fraction Currency Specific
fylein/fyle-teams-app pull request #30
Opened 2022-09-23 11:54 UTC by OmkarJ13

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1bmzzPNBa0pHnMtWUpltkhi1NHJJms2B8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=1atmou-)

2022-09-23 17:14 UTC, abhishek1234321 approved these changes

2022-09-27 06:53 UTC, jatzz10 requested changes
@OmkarJ13 few comments
please fix

2022-09-27 06:53 UTC, jatzz10 commented on fyle_teams_app/libs/utils.py
> +    format_string = '{:,.' + str(currency_precision) + 'f}'
same comments as slack pr for this file
please check @OmkarJ13

2022-09-27 06:53 UTC, jatzz10 commented on fyle_teams_app/ui/cards/notifications.py
> +                                'value': '{}'.format(utils.get_display_amount(report['amount'], report['currency']))
please use a variable `display_account` -
```
display_account = utils.get_display_amount(report['amount'], report['currency'])
```

2022-09-27 06:53 UTC, jatzz10 commented on fyle_teams_app/ui/cards/notifications.py
> +                                'value': '{}'.format(utils.get_display_amount(report['amount'], report['currency']))
same as above comment

2022-09-27 08:56 UTC, OmkarJ13 commented on fyle_teams_app/libs/utils.py
> +    format_string = '{:,.' + str(currency_precision) + 'f}'
Done ✅

2022-09-27 08:56 UTC, OmkarJ13 commented on fyle_teams_app/ui/cards/notifications.py
> +                                'value': '{}'.format(utils.get_display_amount(report['amount'], report['currency']))
Done ✅

2022-09-27 08:57 UTC, OmkarJ13 commented on fyle_teams_app/ui/cards/notifications.py
> +                                'value': '{}'.format(utils.get_display_amount(report['amount'], report['currency']))
Done ✅

2022-09-30 06:16 UTC, jatzz10 approved these changes
lgtm
@OmkarJ13 please make sure to test the full flow of teams-app

2022-10-07 03:04 UTC, merged