Update README.md
fylein/fyle-teams-app pull request #31
Opened 2022-09-23 17:20 UTC by OmkarJ13

2022-09-30 06:15 UTC, jatzz10 requested changes

2022-09-30 06:15 UTC, jatzz10 commented on README.md
>  4. In Developer Tools, go to Tools > Bot Management > New Bot.
`Portal`

2022-09-30 06:15 UTC, jatzz10 commented on README.md
> +    - A .zip file with the name of your app should start downloading.
>identify the app the you just created

How will you create this the first time?

2022-10-03 09:49 UTC, OmkarJ13 commented on README.md
>  4. In Developer Tools, go to Tools > Bot Management > New Bot.
oops, fixed

2022-10-03 09:50 UTC, OmkarJ13 commented on README.md
> +    - A .zip file with the name of your app should start downloading.
This is the initial app that we use as a blueprint which specifies settings, permissions, etc.
We create this from step 9

2022-10-25 05:02 UTC, jatzz10 requested changes

2022-10-25 05:02 UTC, jatzz10 commented on README.md
> +    - A .zip file with the name of your app should start downloading.
then please mention this as well in readme

2022-10-25 05:10 UTC, OmkarJ13 commented on README.md
> +    - A .zip file with the name of your app should start downloading.
yes you're right, fixed this

2022-11-04 10:28 UTC, jatzz10 approved these changes
lgtm omkar ji 🍏

2022-11-04 15:29 UTC, merged