Approver notification & report approve
fylein/fyle-teams-app pull request #5
Opened 2021-12-09 11:41 UTC by shreyanshss7

2021-12-09 11:53 UTC, shreyanshss7 commented on fyle_teams_app/ui/cards/notifications.py
> +expenses = [
This hardcoded response will be removed when we get approver expenses API.

2021-12-14 05:18 UTC, gokulk16 requested changes
some comments. Add the screenshots please.

2021-12-14 05:18 UTC, gokulk16 commented on fyle_teams_app/libs/fyle_utils.py
> +    report_approved_states = ['APPROVED', 'PAYMENT_PENDING', 'PAYMENT_PROCESSING', 'PAID']
instead of using the state names directly, use an enum class
https://www.tutorialspoint.com/enum-in-python

2021-12-14 05:18 UTC, gokulk16 commented on fyle_teams_app/libs/fyle_utils.py
> +    if report['state'] == 'APPROVER_INQUIRY':
can replace the state names with enum
example: expenseStateEnum

2021-12-14 05:18 UTC, gokulk16 commented on fyle_teams_app/libs/fyle_utils.py
> +    can_approve_report = True
should be False initially. can set to True only when the conditions match

2021-12-14 05:18 UTC, gokulk16 commented on fyle_teams_app/libs/fyle_utils.py
> +    elif can_approve_report is True:
should check for the states of the report than checking the default initialized value

2021-12-14 05:18 UTC, gokulk16 commented on fyle_teams_app/libs/fyle_utils.py
> +    elif can_approve_report is True:
should be checking for APPROVER_PENDING state only. 
If for some reason, the DRAFT reports are shown then those could also be allowed to approve which will be wrong.

2021-12-14 05:18 UTC, gokulk16 commented on fyle_teams_app/ui/cards/notifications.py
> +            'type': 'TextBlock',
any links/reference docs to learn about these types in MS teams. I see ColumnSet, TextBlock, Column, Container, FactSet, etc

2021-12-14 05:18 UTC, gokulk16 commented on fyle_teams_app/views/notifications/approver.py
> +        if report['state'] == 'APPROVER_PENDING':
use a enum state

2021-12-14 05:18 UTC, gokulk16 commented on fyle_teams_app/views/notifications/base.py
> +            user = await User.get_by_id(teams_user_id)
assert user found

2021-12-14 06:37 UTC, shreyanshss7 commented on .pylintrc
>  disable=print-statement,
why print statements should be allowed?
We have loggers in case we need to log anything.

2021-12-14 06:39 UTC, shreyanshss7 commented on fyle_teams_app/libs/fyle_utils.py
> +        'REPORT': '{}/app/main/#/enterprise/reports'.format(settings.FYLE_APP_URL),
There would be context lost in reviewing if PR are separate for dependent things.

2021-12-14 06:39 UTC, shreyanshss7 commented on fyle_teams_app/libs/fyle_utils.py
> +    can_approve_report = True
Can you please specify why?

2021-12-14 06:41 UTC, shreyanshss7 commented on fyle_teams_app/libs/fyle_utils.py
> +    elif can_approve_report is True:
Don't understand how would DRAFT reports come for approval? Also the platform API wouldn't allow approving of non ideal (DRAFT) reports to be approved

2021-12-14 06:41 UTC, shreyanshss7 commented on fyle_teams_app/ui/cards/notifications.py
> +            'type': 'TextBlock',
https://adaptivecards.io/explorer/

2021-12-14 06:43 UTC, shreyanshss7 commented on fyle_teams_app/views/notifications/base.py
> +            user = await User.get_by_id(teams_user_id)
There is already an assertion check at line 69 for `user_subscription`, `user_subscription` won't exist without the `user` being present. So assertion check is not required here.

2021-12-14 11:10 UTC, shreyanshss7 commented on fyle_teams_app/libs/fyle_utils.py
> +    if report['state'] == 'APPROVER_INQUIRY':
Hey I've made this change in Spender notifications PR.

2021-12-15 06:25 UTC, abhishek1234321 approved these changes

2021-12-15 06:25 UTC, abhishek1234321 commented on fyle_teams_app/libs/fyle_utils.py
> +        'REPORT': '{}/app/main/#/enterprise/reports'.format(settings.FYLE_APP_URL),
are we not looking to pass `org_id`?

2021-12-15 06:25 UTC, abhishek1234321 commented on fyle_teams_app/libs/fyle_utils.py
> +    report_approved_states = ['APPROVED', 'PAYMENT_PENDING', 'PAYMENT_PROCESSING', 'PAID']
yeah, I think the same

2021-12-15 06:25 UTC, abhishek1234321 commented on fyle_teams_app/libs/fyle_utils.py
> +    can_approve_report = True
as long as we handle all cases initial value can be either IMHO

2021-12-21 11:48 UTC, merged